### ISSUE TITLE
Violations / Denouce API

### ISSUE THREAD

**Issue by kshahzad7** [comsechq/mercadolibre-net-sdk#1]
We were using the API to report violations (denounces) using following api call, which is not working anymore. Can anyone help identity what has changed and whether it is possible using SDK?

https://api.mercadolibre.com/moderations/denounces/items/{0}?access_token={1}

**Comment by bounav** [comment]
Hello,

I had a look in our code and we send the take down requests to that API with the same URL and parameters.
I'm going to assume to send a POST request with the following JSON payload?

```json
{
    "report_reason_id": "string value",
    "comment": "string value"
}
```

If it used to work and now it stopped it could be that your token is expired?

**Comment by bounav** [comment]
I'm going to assume this is no longer an issue having not heard back from you @kshahzad7 ? Feel free to comment.
