### ISSUE TITLE
AuthorizeAsync not working

### ISSUE THREAD

**Issue by Tinchio** [comsechq/mercadolibre-net-sdk#10]
I had a code just like the readme example 

```
meliApi = new MeliApiService(new HttpClient())
                {
                    Credentials = new MeliCredentials(MeliSite.Argentina, clientID, secret)
                };
meliApi.Credentials.TokensChanged += (sender, args) => { doSomethingWithNewTokenValues(args.Info); };

var success = await meliApi.AuthorizeAsync(code, callBackUrl);
```

It was working fine until last update, version 2.0.12
Since then the AuthorizeAsync method is simply returning false, and credential is not getting the access token anymore. 
Any idea why it's not working anymore?
Also, the readme is outdated since it doesn't consider the new httpclient parameter, and this line is wrong
var success = await MercadoLibreApiService.AuthorizeAsync(credentials, code, callBackUrl);
MercadoLibreApiService namespace doesn't belong to this project, and MeliApiService AuthorizeAsync method doesn't support a credentials parameter.

**Comment by bounav** [comment]
Hello,

thanks for spotting the class name that was wrong in the README file.

We updated the README with what should be the correct example.

Did you set the `AccessToken` and `RefreshToken` on the `MeliCredentials` (the new example in README.md now shows that).
