### ISSUE TITLE
Can't install nuget package

### ISSUE THREAD

**Issue by ChriLnth** [comsechq/mercadolibre-net-sdk#2]
When trying to install I get this message "cannot install package MercadoLibreSdk 1.0.8. You´re trying to install the package in a project with .NetFramework 3.5...

I tried with every framework and I still cannot install it. Any solutions?

**Comment by bounav** [comment]
Weird one. We're using that version (v1.0.8) of that nuget package and haven't had any issue.

The project where we use this nuget package is built against .NET 4.7.1 with Visual Studio 2017.

I cloned this project and opened it and it's built against .NET 4.5.1.
