### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by blackzig** [comsechq/mercadolibre-net-sdk#3]
PM> Install-Package MercadoLibreSdk -prerelease
Restaurando pacotes para C:\Users\zigui\source\repos\MonteSeuPCML\MonteSeuPCML\MonteSeuPCML.Android\MonteSeuPCML.Android.csproj...
Install-Package : NU1202: O pacote MercadoLibreSdk 1.0.8 não é compatível com monoandroid81 (MonoAndroid,Version=v8.1). O pacote 
MercadoLibreSdk 1.0.8 dá suporte a: net451 (.NETFramework,Version=v4.5.1)
No linha:1 caractere:1
+ Install-Package MercadoLibreSdk -prerelease
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : A restauração do pacote falhou. Revertendo as alterações no pacote para 'MonteSeuPCML.Android'.
No linha:1 caractere:1
+ Install-Package MercadoLibreSdk -prerelease
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by bounav** [comment]
Hello,

Can you clarify/give us some context regarding your issue? 

What are you trying to achieve?

Thanks,

Ben

**Comment by bounav** [comment]
Not having heard back I'm going to close this issue.

**Comment by bounav** [comment]
Not having heard back I'm going to close this issue.
