### ISSUE TITLE
AuthorizeAsync never returns

### ISSUE THREAD

**Issue by Shivansps** [comsechq/mercadolibre-net-sdk#4]
I get to the point were the app is authorized and i have the code, but AuthorizeAsync never returns.

```csharp
private async Task authAsync ()
{
     var m = new MeliApiService
     {
          Credentials = new MeliCredentials(MeliSite.Argentina, appID, appSecret)
     };

     var redirectUrl = m.GetAuthUrl(appID, MeliSite.Argentina, callbackURL);
     
     String code = null;

     using (var form = new Form2(redirectUrl))
     {
          var result = form.ShowDialog();
          
          if (result == DialogResult.OK)
          {
               code = form.ReturnValue1.Split('=')[1];
               form.Close();
          }
     }

     await m.AuthorizeAsync(code, callbackURL);
     
     richTextBox2.Text = m.Credentials.AccessToken.ToString();
}
```

The code contains the correct token.

`await m.AuthorizeAsync(code, callbackURL);` just never ends. It is also not clear if it wants the redirecturl or the callbackurl since in the example says callback, but in the code it says redirecturl, anyway i tryied them both. 

I've just installed the package using nuget in Visual Studio 2017 and nothing more.

**Comment by bounav** [comment]
Hey sorry, we haven't looked that this project for a while. Is this still an issue? It looks like you are using this in a winform project?

**Comment by MatiasLenk** [comment]
I have the same Issue

**Comment by bounav** [comment]
This issue is super old, I'm closing it but let us know if still a problem and we'll reopen it.
