### ISSUE TITLE
Error in the authentication process

### ISSUE THREAD

**Issue by MatiasLenk** [comsechq/mercadolibre-net-sdk#8]
When I try to authenticate, I get the following error message ...
I am thankful for any kind of help!

var tokens = await SendAsync<TokenResponse>(client, HttpMethod.Post, ApiUrl, "/oauth/token", parameters);
    
--- Error -----
{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  vary: accept
  vary: accept-encoding
  X-Content-Type-Options: nosniff
  X-Request-Id: fc56abdd-569c-418d-bc47-6214926fa7f9
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Headers: Content-Type
  Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
  Access-Control-Max-Age: 86400
  Strict-Transport-Security: max-age=15724800
  X-Cache: Error from cloudfront
  X-Amz-Cf-Pop: EZE51-C1
  X-Amz-Cf-Id: 004seDQhEqkyzVVNvb3-f1EzCL5ZHvR_6KlZ7R4zGfvSjuSt9V4sQg==
  Cache-Control: max-age=0
  Date: Fri, 19 Feb 2021 14:27:14 GMT
  Via: 1.1 171d7370ca264be0e555ac6695616d94.cloudfront.net (CloudFront)
  Content-Type: application/json; charset=UTF-8
}}

**Comment by bounav** [comment]
We've pushed [some changes to authorise with a token in the HTTP request instead of query parameter](https://github.com/comsechq/mercadolibre-net-sdk/commit/a1ed66c2694632d6df01f3f6949782a498d05276). The package should be updated on nuget.

Can you confirm if you still experience the issue?
